added additional test

diff --git a/captagent/init/debian/captagent.init b/captagent/init/debian/captagent.init
--- a/captagent/init/debian/captagent.init
+++ b/captagent/init/debian/captagent.init
@@ -18,14 +18,17 @@ lockfile=/var/lock/$prog
 RETVAL=0
 
 start() {
-	echo -n "Starting $prog: "
-	# there is something at end of this output which is needed to
-	# report proper [ OK ] status in CentOS scripts
-	#$cap $OPTIONS && success || failure
-	start-stop-daemon --start --quiet --pidfile $pidfile --exec $cap -- $OPTIONS || echo "Failed"
-	RETVAL=$?
-	echo
-	[ $RETVAL = 0 ] && touch $lockfile
+  if [ -e /var/run/captagent.pid ]; then
+        echo "[FAILED] Captagent is already running with PID: `cat /var/run/captagent.pid`"
+  else      
+        echo -n "Starting $prog: "
+        # there is something at end of this output which is needed to
+        # report proper [ OK ] status in CentOS scripts
+        start-stop-daemon --start --quiet --pidfile $pidfile --exec $cap -- $OPTIONS || echo "Failed"
+        RETVAL=$?
+        echo
+        [ $RETVAL = 0 ] && touch $lockfile
+  fi
 }
 
 stop() {
